# Generated by Django 6.0.3 on 2026-04-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, default='Anonym', max_length=100),
        ),
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.CharField(blank=True, default='Anonym', max_length=100),
        ),
    ]
