# Generated by Django 6.0.3 on 2026-04-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_review_name_alter_signature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='name',
            field=models.CharField(blank=True, default='Аноним', max_length=100),
        ),
    ]
