# Generated by Django 6.0.3 on 2026-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_signature_ip_address_alter_signature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Auf Moderation'), ('approved', 'Erlaubt'), ('rejected', 'Nicht erlaubt')], default='pending', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
