# Generated by Django 6.0.3 on 2026-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Auf Moderation'), ('approved', 'Erklaubt'), ('rejected', 'Nicht erlaubt')], default='pending', max_length=10),
        ),
    ]
